### ISSUE TITLE
nkit.iso

### ISSUE THREAD

**Issue by zeldaking** [lepelog/sslib#98] opened 2021-06-11 20:21 UTC
Pls make compatible with .nkit.iso

**Comment by lepelog** [comment] 2021-06-16 15:47
Idk what that is, pls be more specific. Is this a duplicate of #86 ?

**Comment by Gudak0** [comment] 2021-07-06 09:44
if you go [here](https://vimm.net/vault/?p=nkit) and grab NKIT 1.4 + Wii partitions you can rebuild the NKIT ISO into a regular .ISO file

**Comment by cjs8487** [comment] 2021-07-07 00:36
Deletion context - the comment contained a link to a website that distributes copyrighted material and was a direct link to downloads containing a specific partition of Wii and GC disc images

**Comment by lepelog** [comment] 2021-07-07 08:12
Information about nkit: https://wiki.gbatemp.net/wiki/NKit
As `wit` doesn't support nkit, this is out of scope for the project, since you can just convert the nkit.iso file to iso using the link I posted

**Closed by lepelog** 2021-07-07 08:12 UTC
